# docker-compose.yml
services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    volumes:
      # Monta a chave da conta de serviço para o BigQuery
      - ./gcp-sa-key.json:/app/gcp-sa-key.json
      # Monta a pasta do frontend para que o FastAPI possa servi-la
      - ./static:/app/static
      # Monta o diretório 'app' inteiro para refletir alterações no código Python sem reconstruir
      - ./app:/app/app
    environment:
      # Aponta para a chave da conta de serviço montada dentro do contêiner
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcp-sa-key.json
      # Define a variável PORT para o ambiente local, simulando o Cloud Run
      PORT: 8080
    restart: always
