services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env    # mantenha este arquivo na raiz
    volumes:
      # chave GCP (opcional em dev; obrigatório se usar BigQuery localmente)
      - type: bind
        source: ./gcp-sa-key.json
        target: /app/gcp-sa-key.json
        read_only: true
      # hot-reload de código (dev)
      - ./static:/app/static
      - ./app:/app/app
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcp-sa-key.json
      PORT: 8080
    restart: always
